services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/graduate_db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev"

  db:
    image: postgres:14
    container_name: graduate_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=graduate123
      - POSTGRES_DB=graduate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
